FROM node:20-slim

RUN useradd -m user

RUN apt-get -y update && apt-get -y install socat

WORKDIR /app

COPY ./index.js .
COPY ./recipes /app/recipes
RUN chown -R root:root /app
RUN chmod -R 555 /app/
RUN chmod 777 /app/recipes
RUN chmod 444 /app/recipes/*.txt

CMD ["socat", "TCP-LISTEN:5000,reuseaddr,fork", "EXEC:'su user -c ./index.js'"]
